---
- name: Upgrade installed packages
  hosts: all
  become: yes
  tasks:

  - name: Upgrade packages
    apt:
      upgrade: dist

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
