# Install packages for Postgres core development
#
- name: Install packages
  hosts: all
  become: yes
  tasks:

  - apt:
      name:
      - build-essential
      - pkgconf
      - libicu-dev
      - bison
      - flex
      - libreadline-dev
      - zlib1g-dev
      - meson
      install_recommends: no
      update_cache: no
